name: Create Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build Booklet
        run: |
          docker run -v "$(pwd)":/home zmotula/pdfjam pdfjam --booklet true --landscape --suffix booklet handbook.pdf
      - name: Build EPUB
        uses: docker://pandoc/core
        with:
          args: "-s -o handbook.epub handbook.md"
      - name: Build MOBI
        uses: docker://larrycai/ebook-convert
        with:
          args: "ebook-convert handbook.epub handbook.mobi"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: TODO
          draft: true
          prerelease: false
      - name: Upload Source PDF
        id: upload-source-pdf
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./handbook.pdf
          asset_name: handbook.pdf
          asset_content_type: application/pdf
      - name: Upload Booklet
        id: upload-booklet-pdf
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./handbook-booklet.pdf
          asset_name: booklet.pdf
          asset_content_type: application/pdf
      - name: Upload EPUB
        id: upload-epub
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./handbook.epub
          asset_name: handbook.epub
          asset_content_type: application/epub+zip
      - name: Upload MOBI
        id: upload-mobi
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./handbook.mobi
          asset_name: handbook.mobi
          asset_content_type: application/x-mobipocket-ebook
      - name: Consolidate artifacts
        run: |
          mkdir dist
          mv handbook.pdf booklet.pdf handbook.epub handbook.mobi dist/
      - name: Upload artifacts
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: data-cesko-digital
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
          AWS_REGION: 'eu-central-1'
          SOURCE_DIR: 'dist'
