name: Create Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create & Upload Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build Booklet
        run: |
          docker run -v "$(pwd)":/home zmotula/pdfjam pdfjam --booklet true --landscape --suffix booklet handbook.pdf
      - name: Build EPUB
        uses: docker://pandoc/core
        with:
          args: "-s -o handbook.epub handbook.md"
      - name: Build MOBI
        uses: docker://larrycai/ebook-convert
        with:
          args: "ebook-convert handbook.epub handbook.mobi"
      - name: Consolidate artifacts
        run: |
          mkdir dist
          mv handbook.pdf booklet.pdf handbook.epub handbook.mobi dist/
      - name: Upload artifacts
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: data-cesko-digital
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
          AWS_REGION: 'eu-central-1'
          SOURCE_DIR: 'dist'
